
server:
    port: 8001

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/store-api

  application:
    name: Product-API
  
  cloud:
    consul:
      discovery:
        health-check-interval: 20s

mongock:
  change-logs-scan-package: com.store.storeproductapi.migrations
  transaction-enabled: true
