# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mongodb-version: [ '5.0' ]

    services:
      keycloak: 
        image: jboss/keycloak:15.0.2
        env:  
          IMPORT: /env/keycloak/store-realm.json
          USERNAME: ${{ secrets.KEYCLOAK_USERNAME }}
          PASSWORD: ${{ secrets.KEYCLOAK_PASSWORD }}
        options: docker run -e KEYCLOAK_USER=${{ env.USERNAME }} -e KEYCLOAK_PASSWORD=${{ env.PASSWORD }} -e KEYCLOAK_IMPORT=${{ env.IMPORT }} -v /env/keycloak/store-realm.json:/env/keycloak/store-realm.json jboss/keycloak
        ports:
          - 8080

      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672

      spring-cloud-consul:
        image: consul:1.11
        ports:
          - "8500:8500"

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
